### ISSUE TITLE
self

### ISSUE THREAD

**Issue by lsbardel** [d3/d3-require#5]
`self` is undefined and causes problems when requiring from node.
```javascript
require('d3-require')
ReferenceError: self is not defined
```
Any reason it is used in this way?

**Comment by mbostock** [comment]
This code is only intended to be run in a browser; it is designed to load [asynchronous module definitions](https://github.com/amdjs/amdjs-api/blob/master/AMD.md) which depend on a global [`define` function](https://github.com/amdjs/amdjs-api/blob/master/AMD.md#define-function-). Also, even if you changed the *self*.define assignment, this code still need *document*.createElement to load the referenced script.

**Comment by lsbardel** [comment]
I understand that point, I'm not planning to use it in node :slightly_smiling_face: .
However, ``d3-selection`` is designed for the browser too right? And you can require it in node.
As it is , I cannot include ``d3-require`` in a custom d3 bundle because of the error above.
Is there any other way I should include the library and not have the ReferenceError? Thanks

**Comment by mbostock** [comment]
Using Browserify, then? How are you generating this bundle? The only bundlers I support are ones that consume the `module` entry point, which is typically Rollup or Webpack, though I think you might be able to use Browserify with Babelify?

Anyway, the short answer is that you may need to change how your bundler is configured, and depending on how your bundler works I may not be able to support it directly.

**Comment by lsbardel** [comment]
OK, thanks for feedback. FYI I use rollup as bundler.
I will find a different solution, possibly not including d3-require directly in the bundle.

**Comment by mbostock** [comment]
Yes, re-reading your comments I don’t think this is a bundler issue, it’s just that you’re trying to load d3-require in Node when that use case is not supported.

(Loading d3-selection in Node *is* explicitly supported. The expectation that you’re also going to load a DOM implementation such as JSDOM, and then pass nodes to d3.select or d3.selectAll rather than relying on a global document.)

For d3-require, I’m not sure what the expectation would be regarding its behavior in a Node environment. I suppose you could asynchronously fetch code and then evaluate it, but the implementation presumably would not use *document*.createElement("script") to do that—you’d need https and eval or vm.
